name: Build Native VR APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      # СКАЧИВАЕМ OPENXR SDK (Без него VR не запустится)
      - name: Download OpenXR SDK
        run: |
          wget https://github.com/KhronosGroup/OpenXR-SDK-Source/releases/download/release-1.1.36/openxr_loader_for_android-1.1.36.tar.gz
          tar -xzf openxr_loader_for_android-1.1.36.tar.gz
          mkdir -p app/src/main/cpp/libs/arm64-v8a
          cp -r openxr_loader_for_android/preload/arm64-v8a/* app/src/main/cpp/libs/arm64-v8a/
          mkdir -p app/src/main/cpp/include/openxr
          cp -r openxr_loader_for_android/include/openxr/* app/src/main/cpp/include/openxr/

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Volleyball-Native-VR
          path: app/build/outputs/apk/debug/app-debug.apk
